### PR TITLE
Elixir 1.7 and Logger Translator

### PR DESCRIPTION
**Pull request by mitchellhenke**
This PR replaces https://github.com/timberio/timber-elixir/pull/299

### CODE REVIEW

**Comment by DavidAntaramian** [comment]
I might have forgotten something, but is this backwards compatible with OTP prior to 21?

**Comment by mitchellhenke** [comment]
@DavidAntaramian yes, it should be.  Travis is running OTP 21.0, 20.3, and 19.3

**Comment by DavidAntaramian** [comment]
Fantastic! :D

**Review by DavidAntaramian — APPROVED** [review]
This looks good to me!

**Pull request merged**
